Initial version

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -13,9 +13,6 @@ on:
           - prepatch
           - preminor
           - premajor
-  release:
-    types:
-      - released
 
 env:
   POETRY_VERSION: '1.1.13'
@@ -30,21 +27,14 @@ jobs:
       - name: Dump workflow context
         uses: crazy-max/ghaction-dump-context@v1
 
-      - name: Input validation
-        if: >-
-          (
-            github.event_name == 'workflow_dispatch' &&
-            github.event.inputs.version-update != 'skip' &&
-            github.ref_protected == 'true'
-          )
+      - name: Branch validation
+        if: github.ref_protected == 'true'
         run: |
-          echo 'ERROR: Version update cannot be performed on a protected branch'
+          echo 'ERROR: Manual deployment cannot be performed on a protected branch.'
           exit 1
 
       - name: Git checkout
         uses: actions/checkout@v3
-        with:
-          token: ${{ steps.token-generation.outputs.token }}
 
       - name: Python setup
         uses: actions/setup-python@v4
@@ -63,12 +53,7 @@ jobs:
 
       - name: Version update
         id: version-update
-        if: >-
-          (
-            github.event_name == 'workflow_dispatch' &&
-            github.ref_protected != 'true' &&
-            github.event.inputs.version-update != 'skip'
-          )
+        if: github.event.inputs.version-update != 'skip'
         run: |
           VERSION=$(poetry version | awk '{print $2}')
 
@@ -78,7 +63,16 @@ jobs:
             poetry version ${{ github.event.inputs.version-update }}; \
           fi
           if [[ "$VERSION" == $(poetry version | awk '{print $2}') ]]; then \
-            echo "ERROR updating the package version"; \
+            echo "ERROR: Updating package version failed."; \
+            exit 1; \
+          fi
+
+      - name: Version validation
+        run: |
+          VERSION=$(poetry version | awk '{print $2}')
+
+          if ! [[ "$VERSION" =~ [a-z] ]]; then \
+            echo "ERROR: Non pre-release version detected."; \
             exit 1; \
           fi
 
@@ -93,8 +87,6 @@ jobs:
       - name: Git commit new version
         if: >-
           (
-            github.event_name == 'workflow_dispatch' &&
-            github.ref_protected != 'true' &&
             github.event.inputs.version-update != 'skip' &&
             steps.version-update.outcome == 'success'
           )
